"""user recording model

Revision ID: 7d4f924e9c38
Revises: 1b905f643ef8
Create Date: 2024-04-03 11:46:09.884636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4f924e9c38'
down_revision: Union[str, None] = '1b905f643ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dataset',
    sa.Column('dataset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.login'], ),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('user_model',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['user_dataset.dataset_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.login'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('user_recording',
    sa.Column('recording_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['user_dataset.dataset_id'], ),
    sa.PrimaryKeyConstraint('recording_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recording')
    op.drop_table('user_model')
    op.drop_table('user_dataset')
    # ### end Alembic commands ###
